version: '3.8'

services:
    backend:
        build: ./backend
        volumes:
            - './backend:/code'
            - 'file-pool:/uploads'
        ports:
            - '3000:3000'
        env_file:
            - backend/.env

    worker:
        build: ./worker
        volumes:
            - './worker:/code'
            - 'file-pool:/uploads'
        # command: npm start

volumes:
    file-pool:
