version: '3.8'

services:
    backend:
        build: ./backend
        volumes:
            - './backend:/code'
            - 'file-pool:/uploads'
        ports:
            - '5000:3000'
        env_file:
            - .env
        networks:
            - message_pipeline
        depends_on: 
            - cache
            - rabbitmq

    worker:
        build: ./worker
        volumes:
            - './worker:/code'
            - 'file-pool:/uploads'
        depends_on:
            - rabbitmq
            - cache
        networks:
            - message_pipeline
        env_file:
            - .env

    rabbitmq:
        image: rabbitmq:3.9-management-alpine
        hostname: 'rabbit-hole'
        ports:
            - '15672:15672'
        env_file:
            - .env
        networks:
            - message_pipeline
    
    cache:
        image: 'redis:6.2.6-alpine'
        hostname: redis-cache
        networks:
            - message_pipeline
        volumes:
            - redis-data:/data


volumes:
    file-pool:
    redis-data:

networks:
    message_pipeline:
