version: '3.8'

services:
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile.dev
            target: dev
        volumes:
            - './frontend:/code'
        ports:
            - '3000:3000'
        networks:
            - main-net
        depends_on: 
            - backend

    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile.dev
            target: dev
        volumes:
            - './backend:/code'
            - 'file-pool:/uploads'
        ports:
            - '5000:5000'
        env_file:
            - .env.local
        networks:
            - message_pipeline
            - main-net
        depends_on: 
            - cache
            - rabbitmq

    worker:
        build: ./worker
        volumes:
            - './worker:/code'
            - 'file-pool:/uploads'
        depends_on:
            - rabbitmq
            - cache
        networks:
            - message_pipeline
        env_file:
            - .env.local

    file-server:
        build: 
            context: ./file-server
            dockerfile: Dockerfile.dev
            target: dev
        volumes:
            - './file-server:/code'
            - 'file-pool:/uploads'
        env_file:
            - .env.local

    rabbitmq:
        image: rabbitmq:3.9-management-alpine
        hostname: 'rabbit-hole'
        ports:
            - '15672:15672'
        env_file:
            - .env.local
        networks:
            - message_pipeline
        restart: always    
    cache:
        image: 'redis:6.2.6-alpine'
        hostname: redis-cache
        networks:
            - message_pipeline
        volumes:
            - redis-data:/data


volumes:
    file-pool:
    redis-data:

networks:
    message_pipeline:
    main-net:
