packages:
  - "frontend"
  - "backend"
  - "worker"

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/client': false
  '@prisma/engines': false
  es5-ext: true
  esbuild: true
  prisma: false
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "es5-ext"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"
  - "@tauri-apps/cli"

peerDependencyRules:
  ignoreMissing:
    - "@prisma/client"
    - "prisma"
